-- MySQL Script generated by MySQL Workbench
-- seg 20 jul 2020 16:45:20 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mart_banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mart_banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mart_banco` DEFAULT CHARACTER SET utf8 ;
USE `mart_banco` ;

-- -----------------------------------------------------
-- Table `mart_banco`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mart_banco`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `sobrenome` VARCHAR(45) NULL,
  `email` VARCHAR(450) NULL,
  `senha` VARCHAR(45) NULL,
  `data_de_nasc` DATE NULL,
  `cidade` VARCHAR(45) NULL,
  `editais_s_n` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mart_banco`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mart_banco`.`empresa` (
  `cnpj` INT NOT NULL,
  `nome_empresa` VARCHAR(100) NULL,
  `email` VARCHAR(450) NULL,
  `senha` VARCHAR(45) NULL,
  `localizacao` VARCHAR(450) NULL,
  `cidade` VARCHAR(45) NULL,
  `tipos_eventos` VARCHAR(45) NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mart_banco`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mart_banco`.`eventos` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  `local` VARCHAR(120) NULL,
  `data_horario` DATETIME NULL,
  `cnpj_empresa` INT NOT NULL,
  `url` VARCHAR(4500) NULL,
  PRIMARY KEY (`id_evento`, `cnpj_empresa`),
  INDEX `fk_eventos_empresa1_idx` (`cnpj_empresa` ASC),
  CONSTRAINT `fk_eventos_empresa1`
    FOREIGN KEY (`cnpj_empresa`)
    REFERENCES `mart_banco`.`empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mart_banco`.`editais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mart_banco`.`editais` (
  `id_edital` INT NOT NULL AUTO_INCREMENT,
  `nome_edital` VARCHAR(450) NULL,
  `data_de_publicacao` DATETIME NULL,
  `publico_alvo` VARCHAR(45) NULL,
  `arquivo` BLOB NULL,
  `empresa_cnpj` INT NOT NULL,
  `descricao_edital` VARCHAR(45) NULL,
  PRIMARY KEY (`id_edital`, `empresa_cnpj`),
  INDEX `fk_editais_empresa1_idx` (`empresa_cnpj` ASC),
  CONSTRAINT `fk_editais_empresa1`
    FOREIGN KEY (`empresa_cnpj`)
    REFERENCES `mart_banco`.`empresa` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mart_banco`.`publico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mart_banco`.`publico` (
  `cliente_id` INT NOT NULL,
  `evento_id` INT NOT NULL,
  PRIMARY KEY (`cliente_id`, `evento_id`),
  INDEX `fk_cliente_has_eventos_eventos1_idx` (`evento_id` ASC),
  INDEX `fk_cliente_has_eventos_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_cliente_has_eventos_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mart_banco`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_eventos_eventos1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `mart_banco`.`eventos` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mart_banco`.`grupos_itinerantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mart_banco`.`grupos_itinerantes` (
  `cnpj_itine` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`cnpj_itine`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mart_banco`.`contratacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mart_banco`.`contratacao` (
  `id_contrato` INT NOT NULL AUTO_INCREMENT,
  `eventos_id_evento` INT NOT NULL,
  `eventos_cnpj_empresa` INT NOT NULL,
  `grupos_itinerantes_contratado` INT NOT NULL,
  `situacao` INT NULL,
  `descricao_funcao` VARCHAR(450) NULL,
  PRIMARY KEY (`id_contrato`),
  INDEX `fk_contratação_eventos1_idx` (`eventos_id_evento` ASC, `eventos_cnpj_empresa` ASC),
  INDEX `fk_contratação_grupos_itinerantes1_idx` (`grupos_itinerantes_contratado` ASC),
  CONSTRAINT `fk_contratação_eventos1`
    FOREIGN KEY (`eventos_id_evento` , `eventos_cnpj_empresa`)
    REFERENCES `mart_banco`.`eventos` (`id_evento` , `cnpj_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contratação_grupos_itinerantes1`
    FOREIGN KEY (`grupos_itinerantes_contratado`)
    REFERENCES `mart_banco`.`grupos_itinerantes` (`cnpj_itine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
